### ISSUE TITLE
Will you release the code for public 

### ISSUE THREAD

**Issue by AaronFengZY** [zhangy76/KNOWN-Hand#1]
I wonder if you will release the code for public, tks.

**Comment by zhangy76** [comment]
I may need one more month to release the code. please let me know if you are in an urgent need

**Comment by AaronFengZY** [comment]
> I may need one more month to release the code. please let me know if you are in an urgent need

Year, I really interested in the loss of prior which mentioned in your paper, could you plz release that part of code first.  Do appreciate！！

**Comment by zhangy76** [comment]
they have been uploaded now. the physics loss will not be uploaded in a near future. please let me know if you have any other questions
